global:
  scrape_interval: 15s  # metrics

scrape_configs:
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:9187']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']  # Loki metrics endpoint
